### ISSUE TITLE
Sending from Android (Quick Share) seems to not work

### ISSUE THREAD

**Issue by Martichou** [vicr123/QNearbyShare#11]
Hey ! First of thanks for the work you've done here.

I built and installed QNearbyShare on Ubuntu 20.04.

The sending from Ubuntu to Android (using Files by Google's receive) works fine.
But sending from Android to Ubuntu seems to not work.
What I'm seeing is the following:

```
rtin :: ~ » /usr/local/libexec/qnearbyshared   
Server Running
Skipped method "NewSession" : Unregistered input type in parameter list: QDBusObjectPath
Pending connection accepted
Accepted connection from Martin's phone
Ready for transfer from remote device:
PIN: 0200
Incoming files:
  llvm.sh   len: 4874   mime: text/x-sh
Accepting transfer from remote device
```

AND

```
rtin :: ~ » /usr/local/bin/qnearbyshare-receive     
Awaiting a Nearby Share connection.
Use Nearby Share on another device to connect to this device to share files.

This Device Name: rtin

Connection established!
Peer Device Name: Martin's phone
PIN: 0200

Files to transfer:
FILE NAME   SIZE
llvm.sh   4.76 KiB

:: Proceed with transfer? [Y/n] y
Starting transfer...
llvm.sh
```

But then nothing more happens. Android will tell me the file is "Sent" after some time.
Checking in my Downloads folder of Ubuntu, I do see the file llvm.sh, but nothing inside, size of 0.

I'm pretty sure the info above are not enough, but if you can guide me to collect more log/anything that can be useful to track down this issue, I'd be happy to!

Cheers,

**Comment by vicr123** [comment]
Hi Martin,

Does the issue persist if you try another file? Or if you try a bigger file?

**Comment by Martichou** [comment]
Hey ! 

I'm sorry but I'll have to admit that I just try again and I cannot reproduce the issue.
Not sure what triggered it in the first place, but we can safely close this :).

Thanks !
