### ISSUE TITLE
sending doesn't work

### ISSUE THREAD

**Issue by ilobilo** [vicr123/QNearbyShare#8]
`qnearbyshare-send` always prints ``No targets found.`` with android "visible to everyone" turned on. wifi and bluetooth are enabled on both devices. also sorry for so many opened issues :D

**Comment by vicr123** [comment]
For Android devices, you'll need to visit the Google Files app and explicitly choose to receive files from Nearby Share. Unfortunately it is not currently known how to make Android display the "Nearby device is sharing" notification at this time.

**Comment by ilobilo** [comment]
ah thanks!
